language: bash
services: docker

env:
  - VERSION=3.6 VARIANT=
  - VERSION=3.6 VARIANT=slim

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
#  - cd "$VERSION/$VARIANT"
  - image="ubuntu:1804"

script:
#  - travis_retry docker build -t "$image" .
#  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
